name: Deploy GitHub Pages

on:
    push:
        branches:
            - prototype3

permissions:
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: prototype3

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v4
              with:
                  personal_token: ${{ secrets.PAGES_TOKEN }}
                  external_repository: lyapjs/lyapjs.github.io
                  publish_dir: ./docs/website
                  publish_branch: main
